# Generated by Django 3.1.1 on 2020-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=300)),
                ('client_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=100)),
                ('amount_to_be_charged', models.IntegerField(max_length=50)),
            ],
        ),
    ]
