# Generated by Django 3.1.1 on 2020-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='amount_to_be_charged',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
